version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.6.8  # primary container for the build job

    steps:
      - checkout
      - run: cat /etc/os-release
      - run: sudo apt update
      - run: sudo apt install default-jre
      - run: java -version
      - run: which java
      - run: echo "export PATH=/home/circleci/.local/bin:$PATH" >> $BASH_ENV  # some python packages get installed  here
      - run: echo $PATH
      - run: python --version
      - run: pip install --upgrade --user pip
      - run: pip list
      - run: python setup.py install  # needed to run the cli unit tests
      - run: make test